#!/usr/bin/env python3
"""Generate a compose override that lets one repo's stack run more than once.

Two things stop a second stack of the same repo from starting, and only two:

  container_name  is hardcoded in these compose files, so the second stack
                  collides on the name no matter what project it belongs to.
  host ports      are fixed, so the second stack collides on the port.

Everything else compose already isolates per project — including NAMED VOLUMES,
which is why a per-project stack gets its own postgres volume and therefore its
own database for free. No database renaming is needed or wanted.

Reads the fully resolved config from `docker compose config --format json`
rather than parsing YAML, so anchors, extends and env interpolation are already
handled by docker itself.

The app service also needs the parent repo's .git mounted at its own absolute
path: in a worktree, .git is a file pointing at a host path with no counterpart
inside the container, and git then fails with "not a git repository" (exit 128).
That mount belongs in the same service block — emitting a second block for the
same service is a duplicate mapping key and compose refuses the file.

Usage: siding-stackgen.py <project> <offset> <config.json> <out.yml>
                          [<app-service> <gitdir-host-path>]
"""
import json
import socket
import sys


def port_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            s.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def main() -> int:
    project, offset, cfg_path, out_path = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    app_svc = sys.argv[5] if len(sys.argv) > 5 else None
    gitdir = sys.argv[6] if len(sys.argv) > 6 else None
    # Volumes to borrow from the shared stack instead of creating empty.
    # "name=external_name" pairs.
    shared = dict(a.split("=", 1) for a in sys.argv[7:]) if len(sys.argv) > 7 else {}
    cfg = json.load(open(cfg_path))
    services = cfg.get("services") or {}

    # Find an offset where every remapped port is free. Walk upward rather than
    # failing: the first guess colliding with something unrelated is common.
    wanted = []
    for svc in services.values():
        for p in svc.get("ports") or []:
            pub = p.get("published")
            if pub:
                wanted.append(int(pub))

    while True:
        if all(port_free(p + offset) for p in wanted):
            break
        offset += 10
        if offset > 40000:
            print("no free port block found", file=sys.stderr)
            return 1

    lines = ["# generated by siding — do not edit", "services:"]
    mapping = []
    for name, svc in services.items():
        body = []
        if svc.get("container_name"):
            body.append(f"    container_name: {project}_{name}")
        ports = svc.get("ports") or []
        if ports:
            # !override, not a plain list: compose MERGES sequences across
            # files, so a plain ports list would publish the original port as
            # well as the remapped one — and the original is exactly what the
            # other stack is already holding.
            body.append("    ports: !override")
            for p in ports:
                pub, target = p.get("published"), p.get("target")
                if not pub:
                    continue
                newp = int(pub) + offset
                proto = p.get("protocol", "tcp")
                body.append(f'      - "{newp}:{target}/{proto}"'
                            if proto != "tcp" else f'      - "{newp}:{target}"')
                mapping.append(f"{name} {pub}->{newp}")
        if app_svc and name == app_svc and gitdir:
            body.append("    volumes:")
            body.append(f"      - {gitdir}:{gitdir}")
        if body:
            lines.append(f"  {name}:")
            lines.extend(body)

    # Data volumes stay per-project — that is what gives each tree its own
    # database. Caches are not data: a fresh project would otherwise re-download
    # every dependency, and for private git-sourced gems that needs credentials
    # the shared stack never had to present, because its cache was already warm.
    if shared:
        lines.append("volumes:")
        for local_name, external_name in shared.items():
            lines.append(f"  {local_name}:")
            lines.append("    external: true")
            lines.append(f"    name: {external_name}")

    open(out_path, "w").write("\n".join(lines) + "\n")
    print(f"offset={offset}")
    for m in mapping:
        print(m)
    return 0


if __name__ == "__main__":
    sys.exit(main())
